//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaLifeStyle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Shipping { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<int> Status { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string ShippingAddress { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
