//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaLifeStyle
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSize
    {
        public int ProductSizeID { get; set; }
        public string ProductSizeName { get; set; }
        public int ProductSubCatID { get; set; }
    
        public virtual ProductSubCategory ProductSubCategory { get; set; }
    }
}
